[package]
name = "qaul-hubd"
version = "0.1.0"
authors = ["Leonora Tindall <nora@nora.codes>", "Katharina Fey <kookie@spacekookie>"]
edition = "2018"

[dependencies]
libqaul = { path = "../../libqaul" }
netmod-tcp = { path = "../../netmod-tcp" }
ratman = { path = "../../ratman" }

async-std = { version = "1.0", features = ["attributes"] }
clap = { version = "2.0", features = ["wrap_help", "color"] }
directories = "2.0"
