stages:
  - test
  - build
  - publish

# Build the Rust root on nightly
build:beta:
  image: instrumentisto/rust:1.39.0-beta
  script:
    - cargo test
    - cargo build

# Run test suite
test_webgui:
  stage: test
  image: circleci/node:10-browsers
  cache:
    key: yarn
    paths:
      - webgui/.yarn
  script:
    - cd webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run test
    - yarn run lint:hbs
    - yarn run lint:js

build_webgui:
  stage: build
  image: node:10
  cache:
    key: yarn
    paths:
      - webgui/.yarn
  script:
    - cd webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run build --prod
  artifacts:
    paths:
      - webgui/dist/
