stages:
  - build
  - test
  - deploy
  - cleanup

Debian 8 64-bit:
  stage: build
  script:
    - mkdir build; cd build; cmake ..; make package
  tags:
    - debian8_64

Debian 8 32-bit:
  stage: build
  script:
    - mkdir build; cd build; cmake ..; make package
  tags:
    - debian8_32

OSX 10.6:
  stage: build
  script:
    - mkdir build; cd build; cmake ..; make
    - ./make_dmg.sh
  tags:
    - osx_10.6

Android:
  stage: build
  script:
    - mkdir build; cd build
    - cmake ../ -DPORT=ANDROID -DNDK_ROOT=$ANDROID_NDK -DEXTRALIB_PATH=$ANDROID_LIBRARIES
    - make
  tags:
    - android
