[package]
name = "alexandria"
description = "A powerful, multi-payload, zone-encrypted persistence store"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
