[workspace]
members = [
    # Main storage database
    "alexandria",

    # qaul.net service library
    "libqaul",

    # libqaul additions
    "libqaul/http",
    "libqaul/rpc",
    "libqaul/ipc",
    "libqaul/ws",

    # qaul.net main services
    "libqaul/service/chat",
    # "libqaul/service/feed",
    "libqaul/service/files",
    "libqaul/service/voices",

    # decentralised routing protocol
    "ratman",
    "ratman/harness",
    "ratman/identity",
    "ratman/netmod",

    # Various utility crates
    "clockctrl",
    "permute",
    "visn",
    "async-notify",
    
    # Available netmod drivers
    "netmod-mem",
    "netmod-udp",
    "netmod-wd",
    "netmod-overlay",

    # infrastructure crates
    "qaulhubd",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli",
    "clients/linux-daemon",

    # Android specifics
    "librobot",

    # test binaries
    "clients/linux-http-test",
    "clients/linux-voice-test",
    # "clients/http-test"
]
