[package]
name = "alexandria"
description = "A zone-encrypted, user-namespaced, hybrid database with tag based query support"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
repository = "https://git.open-communication.net/qaul/alexandria"
documentation = "https://docs.rs/alexandria"
license = "GPL-3.0"
edition = "2018"

[dependencies]
identity = { version = "0.3", features = ["digest", "random"], package = "ratman-identity" }

async-std = { version = "1.0", features = ["unstable"] }
serde = { version = "1.0", features = ["derive"] }
sodiumoxide = "0.2.5"

