[package]
name = "qaul-files"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
identity = { path = "../../../ratman/identity", features = ["digest"], package = "ratman-identity" }
libqaul = { path = "../../" }


async-std = "=1.5"
bincode = "1.0"
mime = "0.3"
mime_guess = "2.0.1"
serde = { version = "1.0" }
tracing = "0.1"
tracing-futures = "0.2"
