[package]
name = "qaul-chat"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
libqaul = { path = "../../", features = ["testing"] }
files = { path = "../files", package = "qaul-files" }

async-std = "1.0"
chrono = { version = "0.4", features = ["serde"] }
conjoiner = { version = "1.2", package = "conjoiner-engine" }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
netmod-mem = { path = "../../../netmod-mem" }
ratman = { path = "../../../ratman" }
tempfile = "3.0"