[package]
name = "qaul-chat"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
files = { path = "../files", package = "qaul-files" }
libqaul = { path = "../../", features = ["testing"] }

async-std = "=1.5"
bincode = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-futures = "0.2" 

[dev-dependencies]
tracing-subscriber = "0.2"
ratman-harness = { path = "../../../ratman/harness" }
tempfile = "3.0"