[package]
name = "ratman-identity"
description = "A small crate that provides an identity abstraction for RATMAN"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[features]
digest = ["blake2"]

[dependencies]
blake2 = { version = "0.8.0", optional = true }
serde = { version = "1.0.0", features = ["derive"] }
hex = "0.4"
