[package]
name = "qauld"
version = "0.1.0"
authors = ["qaul.net community <contact@qaul.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
async-std = { version = "1.9", features = ["attributes"] }
futures = "0.3.15"
log = "0.4"
pretty_env_logger = "0.4"
prost = "0.9.0"
state = "0.5"
bs58 = "0.4"
