[package]
name = "access-notifier"
version = "0.1.0"
authors = ["Leonora Tindall <nora@nora.codes>"]
edition = "2018"
description = "Notify async tasks when someone mutates data they're interested in."
license = "AGPL-3.0"
