name: qaul_rpc
description: RPC Connection between the Flutter app & qaul-rpc.
version: 0.0.1

publish_to: 'none'

flutter:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_base58: ^0.2.1

  path: ^1.8.0

  ffi: ^1.1.2
  convert: ^3.0.1
  protobuf: ^2.0.0
  
  equatable: ^2.0.3
  hooks_riverpod: ^1.0.0-dev.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
