[package]
name = "libqaul-ws"
description = "A websocket RPC layer for libqaul"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>", "Katharina Fey <kookie@spacekookie.de"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
async-tungstenite = "0.4"
futures = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

libqaul = { path = ".." }
libqaul-rpc = { path = "../rpc" }
