[package]
name = "ratman-netmod"
version = "0.1.0"
authors = [
  "Katharina Fey <kookie@spacekookie.de>",
  "Leonora Tindall <nora@nora.codes>"
]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
identity = { path = "../identity", package = "ratman-identity" }
serde = { version = "1.0", features = ["derive"] }
twox-hash = "1.5"
