[package]
name = "ratman"
description = "A fully delay tolerant, decentralised userspace routing protocol"
license = "AGPL-3.0"
version = "0.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
conjoiner = { git = "https://git.open-communication.net/qaul/conjoiner-engine", package = "conjoiner-engine" }
serde = { version = "1.0", features = ["derive"] }

twox-hash = "1.5"

# Sub-components
identity = { path = "identity", package = "ratman-identity" }
netmod = { path = "netmod", package = "ratman-netmod"}
