name: logger
description: Logging Package
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3

  archive: ^3.1.8
  path_provider: ^2.0.8
  neat_periodic_task: ^2.0.0
  shared_preferences: ^2.0.12

  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0

  mailto: ^2.0.0
  url_launcher: ^6.0.18
  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
