name: qaul
version: 2.0.0-beta.12
summary: qaul - Internet Independent Wireless Mesh Communication App
description: Communicate directly from device to device via your local wifi network, or via the shared wifi network of your phone. Mesh local clouds together via manually added static nodes. Use this peer to peer communication method to communicate internet independently and completely off-the-grid.

base: core22

grade: devel
confinement: strict


parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    source-depth: 1
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter channel stable
      flutter upgrade
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  libqaul:
    plugin: rust
    source: https://github.com/qaul/qaul.net.git
    after: [rust-deps]
    build-packages:
      - protobuf-compiler
    override-build: |
      cd rust || exit 1
      cargo build --release
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      cp target/release/liblibqaul.so $SNAPCRAFT_PART_INSTALL/bin/lib

  qaul:
    plugin: nil
    source: .
    after: [flutter-git]
    override-build: |
      set -eux
      flutter pub get || true
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/gui
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
      cp -r snap/gui/* $SNAPCRAFT_PART_INSTALL/gui/


environment:
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/bin/lib


slots:
  dbus-qaul:
    interface: dbus
    name: net.qaul.app
    bus: session


apps:
  qaul:
    command: bin/qaul
    desktop: gui/qaul.desktop
#    common-id: net.qaul.app.desktop
#    extensions: [gnome]
    extensions:
      - gnome-3-38
    plugs:
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - network-manager
      - network-manager-observe
      - process-control
    slots:
      - dbus-qaul
