[book]
authors = ["Katharina Fey", "Mathias Jud", "Jess 3Jane"]
multilingual = false
src = "src"
title = "qaul.net Contributors Manual"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://git.open-communication.net/qaul/qaul.net/-/tree/master/docs%2Fcontributors"
git-repository-icon = "fa-git"
