[package]
name = "libqaul"
description = "Abstraction for building services over internet independent networks"
version = "0.1.0"
authors = [ "Katharina Fey <kookie@spacekookie.de>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
identity = { path = "../ratman/identity", package = "ratman-identity", features = ["digest"] }
platform = { path = "platform", package = "qaul-platform" }
ratman = { path = "../ratman" }

async-std = "0.99"
alexandria = { git = "https://git.open-communication.net/qaul/alexandria" }
conjoiner = { version = "1.0", package = "conjoiner-engine" }
serde = { version = "1.0", features = [ "derive" ] }
base64 = "0.10"
blake2 = "0.8.0"
mime = "0.3"
rand = "0.7"

