[package]
name = "libqaul"
description = "Abstraction for building services over internet independent networks"
version = "0.1.0"
authors = [ "Katharina Fey <kookie@spacekookie.de>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
alexandria = { version = "0.2", path = "../alexandria" }
ratman = { path = "../ratman" }

async-std = { version = "1.0", features = ["attributes", "unstable"] }
base64 = "0.10"
blake2 = "0.8"
conjoiner = { version = "1.2", package = "conjoiner-engine" }
crossbeam-channel = "0.4"
ed25519-dalek = "1.0.0-pre.3"
futures = "0.3"
hex = "0.4"
mime = "0.3"
rand = "0.7"
serde = { version = "1.0", features = [ "derive" ] }
tempfile = { version = "3.0", optional = true }
tracing = "0.1"
tracing-futures = "0.2"
netmod-mem = { path = "../netmod-mem", optional = true }

[dev-dependencies]
serde_json = "1.0"
bincode = "1.0"
tempfile = "3.0"

[features]
default = ["generate-message", "testing"]
generate-message = []
testing = ["tempfile", "netmod-mem"]